# Generated by Django 3.2.9 on 2021-11-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitcoin',
            old_name='semantics',
            new_name='semantics_all',
        ),
        migrations.RemoveField(
            model_name='bitcoin',
            name='tweet_content',
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='high_price_24h',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='market_dominance_percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='price_change_percentage_24h',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='semantics_negative_tweets',
            field=models.FloatField(default=-2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='semantics_positive_tweets',
            field=models.FloatField(default=-2),
            preserve_default=False,
        ),
    ]
