# Generated by Django 3.2.9 on 2021-11-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211124_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoin',
            name='keyword_tweet_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
