# Generated by Django 3.2.9 on 2021-11-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bitcoin_keyword_tweet_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethereum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('price_change_percentage_24h', models.FloatField()),
                ('high_price_24h', models.FloatField()),
                ('market_dominance_percentage', models.FloatField()),
                ('keyword_tweet_number', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('semantics_all', models.FloatField()),
                ('semantics_positive_tweets', models.FloatField()),
                ('semantics_negative_tweets', models.FloatField()),
            ],
        ),
    ]
