# Generated by Django 3.2.9 on 2021-11-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_solana'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoin',
            name='circulating_supply',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='total_supply',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ethereum',
            name='circulating_supply',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ethereum',
            name='total_supply',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solana',
            name='circulating_supply',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solana',
            name='total_supply',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
    ]
