# Generated by Django 3.2.9 on 2021-11-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211124_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitcoin',
            name='total_supply',
        ),
        migrations.RemoveField(
            model_name='ethereum',
            name='total_supply',
        ),
        migrations.RemoveField(
            model_name='solana',
            name='total_supply',
        ),
    ]
