# Generated by Django 3.2.9 on 2021-11-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211124_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoin',
            name='percentage_of_negative_tweets',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='percentage_of_neutral_tweets',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='percentage_of_positive_tweets',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ethereum',
            name='percentage_of_negative_tweets',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ethereum',
            name='percentage_of_neutral_tweets',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ethereum',
            name='percentage_of_positive_tweets',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solana',
            name='percentage_of_negative_tweets',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solana',
            name='percentage_of_neutral_tweets',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solana',
            name='percentage_of_positive_tweets',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
