# Generated by Django 3.2.9 on 2021-11-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211127_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoin',
            name='low_price_24h',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ethereum',
            name='low_price_24h',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solana',
            name='low_price_24h',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
