# Generated by Django 3.2.9 on 2022-03-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211130_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomTweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_tweet', models.CharField(max_length=300)),
                ('btc_eval', models.FloatField()),
                ('eth_tweet', models.CharField(max_length=300)),
                ('eth_eval', models.FloatField()),
                ('sol_tweet', models.CharField(max_length=300)),
                ('sol_eval', models.FloatField()),
            ],
        ),
    ]
