# Generated by Django 3.2.9 on 2022-03-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_randomtweets'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomTweetBTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=300)),
                ('eval', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RandomTweetETH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=300)),
                ('eval', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RandomTweetSOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=300)),
                ('eval', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='RandomTweets',
        ),
    ]
