# Generated by Django 3.2.9 on 2022-03-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220304_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomtweetbtc',
            name='cleaned_tweet',
            field=models.CharField(default='das', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='randomtweeteth',
            name='cleaned_tweet',
            field=models.CharField(default='dasdas', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='randomtweetsol',
            name='cleaned_tweet',
            field=models.CharField(default='dsadasd', max_length=300),
            preserve_default=False,
        ),
    ]
